/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type LoanId = bigint;
export type ProducerId = bigint;
export interface Type {
  'name' : string,
  'canSelfView' : boolean,
  'producerNumber' : string,
  'phone' : string,
}
export interface Type__1 {
  'producerId' : ProducerId,
  'date' : string,
  'amount' : number,
  'reason' : string,
}
export interface Type__2 {
  'producerId' : ProducerId,
  'date' : string,
  'ratePerLitre' : number,
  'session' : string,
  'fatPercent' : number,
  'amount' : number,
  'litres' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProducer' : ActorMethod<[string, string, string], ProducerId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyHistory' : ActorMethod<
    [string],
    {
      'advances' : Array<Type__1>,
      'producer' : Type,
      'milkEntries' : Array<Type__2>,
    }
  >,
  'getProducerById' : ActorMethod<[ProducerId], [] | [Type]>,
  'getProducerByPhone' : ActorMethod<[string], [] | [Type]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordAdvance' : ActorMethod<[ProducerId, string, number, string], bigint>,
  'recordLoan' : ActorMethod<[ProducerId, string, number, string], LoanId>,
  'recordMilkEntry' : ActorMethod<
    [ProducerId, string, string, number, number, number],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSelfViewPermission' : ActorMethod<[ProducerId, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];