/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProducerId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Type__1 = IDL.Record({
  'producerId' : ProducerId,
  'date' : IDL.Text,
  'amount' : IDL.Float64,
  'reason' : IDL.Text,
});
export const Type = IDL.Record({
  'name' : IDL.Text,
  'canSelfView' : IDL.Bool,
  'producerNumber' : IDL.Text,
  'phone' : IDL.Text,
});
export const Type__2 = IDL.Record({
  'producerId' : ProducerId,
  'date' : IDL.Text,
  'ratePerLitre' : IDL.Float64,
  'session' : IDL.Text,
  'fatPercent' : IDL.Float64,
  'amount' : IDL.Float64,
  'litres' : IDL.Float64,
});
export const LoanId = IDL.Nat;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProducer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ProducerId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyHistory' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'advances' : IDL.Vec(Type__1),
          'producer' : Type,
          'milkEntries' : IDL.Vec(Type__2),
        }),
      ],
      ['query'],
    ),
  'getProducerById' : IDL.Func([ProducerId], [IDL.Opt(Type)], ['query']),
  'getProducerByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Type)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAdvance' : IDL.Func(
      [ProducerId, IDL.Text, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'recordLoan' : IDL.Func(
      [ProducerId, IDL.Text, IDL.Float64, IDL.Text],
      [LoanId],
      [],
    ),
  'recordMilkEntry' : IDL.Func(
      [ProducerId, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSelfViewPermission' : IDL.Func([ProducerId, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProducerId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Type__1 = IDL.Record({
    'producerId' : ProducerId,
    'date' : IDL.Text,
    'amount' : IDL.Float64,
    'reason' : IDL.Text,
  });
  const Type = IDL.Record({
    'name' : IDL.Text,
    'canSelfView' : IDL.Bool,
    'producerNumber' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Type__2 = IDL.Record({
    'producerId' : ProducerId,
    'date' : IDL.Text,
    'ratePerLitre' : IDL.Float64,
    'session' : IDL.Text,
    'fatPercent' : IDL.Float64,
    'amount' : IDL.Float64,
    'litres' : IDL.Float64,
  });
  const LoanId = IDL.Nat;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProducer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ProducerId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyHistory' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'advances' : IDL.Vec(Type__1),
            'producer' : Type,
            'milkEntries' : IDL.Vec(Type__2),
          }),
        ],
        ['query'],
      ),
    'getProducerById' : IDL.Func([ProducerId], [IDL.Opt(Type)], ['query']),
    'getProducerByPhone' : IDL.Func([IDL.Text], [IDL.Opt(Type)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAdvance' : IDL.Func(
        [ProducerId, IDL.Text, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'recordLoan' : IDL.Func(
        [ProducerId, IDL.Text, IDL.Float64, IDL.Text],
        [LoanId],
        [],
      ),
    'recordMilkEntry' : IDL.Func(
        [ProducerId, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSelfViewPermission' : IDL.Func([ProducerId, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };